[project]
name = "solar-robot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opencv-python",
    "numpy",
    "pyserial",
    "smbus2",
    "adafruit-blinka",
    "adafruit-circuitpython-vl53l0x",
    "adafruit-lgpio",
]
